In [2]:
import numpy as np

x  = np.array([1,5,9,6,8])
type(x)

numpy.ndarray

In [6]:
y = np.array([[1,2,6,8],[8,6,4,5]])
print(y)

[[1 2 6 8]
 [8 6 4 5]]


In [7]:
print(y.ndim, y.shape, y.size, y.dtype, y.itemsize, y.nbytes)

2 (2, 4) 8 int32 4 32


In [16]:
y = np.array([[1,2,3,4],[5,6,7,8]],dtype='float')
print(y)
print(y.dtype)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]]
float64


In [19]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [20]:
y = np.array([[1,2,3,4],[5,6,7,8]],dtype='int64')
print(y)
print(y.itemsize)

[[1 2 3 4]
 [5 6 7 8]]
8


In [32]:
n = [5, 10, 15, 20, 25]
x = np.array(n)
print(type(x))
print(x.ndim, x.shape, x.size)

<class 'numpy.ndarray'>
1 (5,) 5


In [33]:
n = [[-1, -2, -3, -4], [-2,-4, -6, -8]]
y = np.array(n)
print(type(y))
print(y.ndim, y.shape, y.size, y.dtype, y.itemsize)

<class 'numpy.ndarray'>
2 (2, 4) 8 int32 4


In [40]:
a = [[[4.1, 2.5], [1.1, 2.3], [9.1, 2.5]], [[8.6, 9.9],[3.6, 4.3], [6.6, 0.3]]]
x = np.array(a,dtype='float64')
type(x), x.dtype, x.shape

(numpy.ndarray, dtype('float64'), (2, 3, 2))

In [45]:
x = np.zeros((2,4))
print(x)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [48]:
x = np.zeros(shape = (2,4),dtype='int')
print(x)

[[0 0 0 0]
 [0 0 0 0]]


In [49]:
y = np.full(shape= (2,3), fill_value=23)
print(y)

[[23 23 23]
 [23 23 23]]


In [52]:
x = np.arange(3,15,2.5)
print(x)

[  3.    5.5   8.   10.5  13. ]


In [53]:
x = np.linspace(3,15,5)
print(x)

[  3.   6.   9.  12.  15.]


In [55]:
np.random.seed(100)
x = np.random.rand(2)
print(x)

[ 0.54340494  0.27836939]


In [56]:
x = np.random.randint(10,50,6)
print(x)

[33 25 20 40 44 12]


In [70]:
# Standard normal distribution
np.random.seed = 100
x = np.random.randn(4)
print(x)

[-1.11831825  1.61898166  1.54160517 -0.25187914]


In [73]:
# normal distribution with mean 10 and sd 2
#set seed as 100
np.random.seed =100

x = 10 + 2*np.random.randn(3) 
print(x)

[ 11.46200069  12.72311225   9.34752388]


In [86]:
np.random.seed = 100
x = 10 + 2*np.random.randn(10000)
print(x.std(),x.mean())

2.02266771915 10.0040700574


In [89]:
# Reading Data from a file

from io import StringIO

x = StringIO('''88.25 93.45 72.60 90.90
72.3 78.85 92.15 65.75
90.5 92.45 89.25 94.50
''')

d = np.loadtxt(x,delimiter=' ')
print(d)
print(type(d),d.dtype, d.ndim, d.shape)

[[ 88.25  93.45  72.6   90.9 ]
 [ 72.3   78.85  92.15  65.75]
 [ 90.5   92.45  89.25  94.5 ]]
<class 'numpy.ndarray'> float64 2 (3, 4)


In [90]:
np.random.rand(2,3)

array([[ 0.37791878,  0.5578307 ,  0.3626368 ],
       [ 0.906111  ,  0.20198801,  0.5502618 ]])

In [95]:
import numpy as np

print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [97]:
x1 = np.array( [[[-1,1],[-2,2]],[[-3 ,3], [-4, 4]]] )
print (x1.ndim, x1.shape, x1.size)

3 (2, 2, 2) 8


In [100]:
x2 = np.ones(shape = (3,2,2))
print(x2)

x3 = np.eye(4)
print(x3)

[[[ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [101]:
x4 = np.random.rand(3,4,2)
print(x4)

[[[ 0.98856748  0.71424492]
  [ 0.53241104  0.6609214 ]
  [ 0.18343567  0.58564401]
  [ 0.58203101  0.58821186]]

 [[ 0.13868864  0.57575239]
  [ 0.38649619  0.97895376]
  [ 0.79364109  0.97386859]
  [ 0.44606073  0.49125144]]

 [[ 0.16906892  0.3176221 ]
  [ 0.9448535   0.45043741]
  [ 0.4693901   0.73987985]
  [ 0.73555026  0.57949203]]]


In [104]:
x6 = np.arange(2,42,2)
print(x6)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [105]:
x7 = np.linspace(10,20,30)
print(x7)

[ 10.          10.34482759  10.68965517  11.03448276  11.37931034
  11.72413793  12.06896552  12.4137931   12.75862069  13.10344828
  13.44827586  13.79310345  14.13793103  14.48275862  14.82758621
  15.17241379  15.51724138  15.86206897  16.20689655  16.55172414
  16.89655172  17.24137931  17.5862069   17.93103448  18.27586207
  18.62068966  18.96551724  19.31034483  19.65517241  20.        ]


In [109]:
# Reshaping ndarrays
# Shape of an array can be changed using reshape.

np.random.seed = 100
x = np.random.randint(10,100,8)
print(x,end='\n\n')

y = x.reshape(2,4)
print(y,end='\n\n')

z = x.reshape(2,2,2)
print(z)

[34 81 75 66 77 62 92 39]

[[34 81 75 66]
 [77 62 92 39]]

[[[34 81]
  [75 66]]

 [[77 62]
  [92 39]]]


In [117]:
# Stacking arrays vertically
# Two or more arrays can be joined vertically using the generic vstack method.

x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
print(x,y,sep='\n\n')

print('\nvertically stacked')

np.vstack((x,y))

[[-1  1]
 [-3  3]]

[[-2  2]
 [-4  4]]

vertically stacked


array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

In [119]:
# Stacking arrays horizontally
# Two or more arrays can be joined horizontally using the generic hstack method.

x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z = np.array([[-5, 5], [-6, 6]])
print(x,y,z,sep='\n\n')

print('\nvertically stacked')

np.hstack((x,y,z))

[[-1  1]
 [-3  3]]

[[-2  2]
 [-4  4]]

[[-5  5]
 [-6  6]]

vertically stacked


array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

In [126]:
# Splitting arrays vertically

x = np.arange(30).reshape(6,5)
print(x)
print()
split = np.vsplit(x,2)
print(split[0])
print()
print(split[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [136]:
x = np.arange(30).reshape(6,5)
print(x,end='\n\n')

split = np.vsplit(x,(2,5))
print(split[0],end = '\n\n')
print(split[1],end = '\n\n')
print(split[2],end = '\n\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[25 26 27 28 29]]



In [139]:
x = np.arange(10).reshape(2, 5)
print(x, end='\n\n')
res = np.hsplit(x, (2,4))
print(res[0], end='\n\n')
print(res[1], end='\n\n')
print(res[2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [5 6]]

[[2 3]
 [7 8]]

[[4]
 [9]]


In [144]:
x = np.arange(6).reshape(2,3)
print(x)
y = np.hsplit(x,(2,))
print(y[0])
print(y[1])

[[0 1 2]
 [3 4 5]]
[[0 1]
 [3 4]]
[[2]
 [5]]


In [148]:
x = np.arange(4).reshape(2,2)
y = np.arange(4, 8).reshape(2,2)
print(x,y,sep='\n\n',end='\n\n')
print(np.hstack((x,y)))

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]

[[0 1 4 5]
 [2 3 6 7]]


In [151]:
x = np.arange(1,21)
print(x)
print(x.shape)
y = x.reshape(2,10)
print(y)
np.hsplit(y,2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


[array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]]), array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]])]

In [154]:
z = x.reshape(4,5)
z
print(np.vsplit(z,2))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]


In [160]:
p = np.array([3, 6, 9, 12]).reshape(2,2)
q = np.array([15, 18, 21, 24, 27, 30]).reshape(2,3)
print(p,q,sep='\n\n',end='\n\n')
print(np.hstack((p,q)))

[[ 3  6]
 [ 9 12]]

[[15 18 21]
 [24 27 30]]

[[ 3  6 15 18 21]
 [ 9 12 24 27 30]]


In [161]:
# Basic Operations with Scalars

x = np.arange(6).reshape(2,3)
print(x)
print(x+10)
print(x%2)
print(x*2)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[0 1 0]
 [1 0 1]]
[[ 0  2  4]
 [ 6  8 10]]


In [168]:
x = np.array([[-1,1],[-2,2]])
y = np.array([[4,-4],[5,-5]])

print(x,y,sep='\n\n',end='\n\n')
print(x+y,end='\n\n')
print(x*y)

[[-1  1]
 [-2  2]]

[[ 4 -4]
 [ 5 -5]]

[[ 3 -3]
 [ 3 -3]]

[[ -4  -4]
 [-10 -10]]


In [169]:
x = np.array([[-1, 1], [-2, 2]])
y = np.array([-10, 10])
print(x,y,sep='\n\n',end='\n\n')
print(x * y)

[[-1  1]
 [-2  2]]

[-10  10]

[[10 10]
 [20 20]]


In [174]:
x = np.arange(6).reshape()
y = np.arange(12).reshape(4,3)
print(x,y,sep='\n\n',end='\n\n')


ValueError: cannot reshape array of size 6 into shape (2,)

In [175]:
x = np.array([[0,1], [2,3]])
print(np.square(x))
print(np.sin(x))

[[0 1]
 [4 9]]
[[ 0.          0.84147098]
 [ 0.90929743  0.14112001]]


In [177]:
x = np.array([[0,1], [2, 3]])
print(x, end='\n\n')
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=1,keepdims=True), end='\n\n')

[[0 1]
 [2 3]]

6

[2 4]

[[1]
 [5]]



In [178]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]


In [179]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x.dot(y))

[[ 6 -6]
 [-6  6]]


In [180]:
print(x.tolist())

[[-2], [2]]


In [181]:
x = np.arange(4)
print(x**2)

[0 1 4 9]


In [182]:
import numpy as np

print(np.repeat(3, 4))

[3 3 3 3]


In [184]:
x = np.arange(20).reshape(4,5)
print(x)
print(x.mean(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[  2.   7.  12.  17.]


In [186]:
x = np.arange(30).reshape(5,6)
print(x)
print(x.argmax(axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[5 5 5 5 5]


In [190]:
np.random.rand(5,8,2) * np.random.rand(2,)

array([[[ 0.52396226,  0.20122834],
        [ 0.21554275,  0.51359692],
        [ 0.65610657,  0.31028412],
        [ 0.33696585,  0.01644841],
        [ 0.24541089,  0.68433623],
        [ 0.50461501,  0.43775817],
        [ 0.10827343,  0.39359986],
        [ 0.43660705,  0.44071626]],

       [[ 0.19346285,  0.06067577],
        [ 0.56635874,  0.54656185],
        [ 0.69748185,  0.16216987],
        [ 0.5738721 ,  0.33964128],
        [ 0.21862563,  0.27364012],
        [ 0.30680935,  0.59715174],
        [ 0.68352068,  0.03943791],
        [ 0.45262212,  0.16337214]],

       [[ 0.676965  ,  0.64850135],
        [ 0.65383901,  0.44107331],
        [ 0.49793463,  0.21447807],
        [ 0.40511743,  0.41408351],
        [ 0.25886279,  0.69128004],
        [ 0.63076012,  0.05691771],
        [ 0.46445297,  0.11292491],
        [ 0.05282091,  0.53321803]],

       [[ 0.54723576,  0.53696687],
        [ 0.22829693,  0.10027839],
        [ 0.04608852,  0.13898097],
        [ 0.41665191, 

In [188]:
x = np.arange(4).reshape(2,2)
print(np.isfinite(x))

[[ True  True]
 [ True  True]]


In [193]:
x = np.random.randint(-30,30,30).reshape(5,6)
print(x)
print(x.sum())
print(x.sum(axis=0,keepdims=1))
print(x.sum(axis=1,keepdims=1))

[[ 11 -15 -14 -10   9  12]
 [ 17  23  -2 -16  29 -22]
 [ -5  25 -12 -13   8  -2]
 [  1   5  25 -16  -5 -13]
 [ 10 -19  -6  23  14 -21]]
21
[[ 34  19  -9 -32  55 -46]]
[[-7]
 [29]
 [ 1]
 [-3]
 [ 1]]


In [198]:
x = 10 + 2*np.random.randn(50)
print(x,x.shape)
print(x.mean())
print(x.std())
print(x.var())

[ 13.80737931   8.41669982  10.62194602  13.24078312   7.44157049
  10.27900179   9.34800385   8.45921573  10.54647658   7.08120059
   8.92193181  11.32416739  11.0170341    8.96880093  10.51393895
  11.08197393  11.8526174    6.43520819  13.26877588  13.15618207
   8.86677259   7.82168232   8.60226361   8.34311235   7.40585214
   9.81071825  11.41628811  10.58559656   9.94095302  10.45459706
  12.16447623  10.03688851   7.36484602   5.20924291  10.26951769
  10.60243627   8.74556216  11.38069437   8.44084318  12.56148312
   9.98446383  11.58810415  10.00984985   5.98132997   8.55280474
   8.44478655  11.6231478   10.5521426    5.47595438  10.0316508 ] (50,)
9.76101938168
2.00323003345
4.01293056693


In [199]:
y = np.array([[0, 1, 2],
              [3, 4, 5]])
print(y[1:2, 1:3]) 
print(y[1])   
print(y[:, 1]) 


[[4 5]]
[3 4 5]
[1 4]


In [201]:
x = np.array([[0,1], [2, 3]])
print(x)
for a in np.nditer(x):
    print(a)

[[0 1]
 [2 3]]
0
1
2
3


In [202]:
x = np.arange(10).reshape(2,5)
print(x)
BoolArray = x%2 ==0
print(BoolArray)
print(x[BoolArray])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ True False  True False  True]
 [False  True False  True False]]
[0 2 4 6 8]


In [206]:
x = np.arange(10)
print(x.flatten())

[0 1 2 3 4 5 6 7 8 9]


In [208]:
x = np.array([[0, 1], [1, 1], [2, 2]])
print(x)
print(x.sum(-1))

[[0 1]
 [1 1]
 [2 2]]
[1 2 4]


In [209]:
x = np.arange(30).reshape(3,5,2)
print(x[1,::2,1])

[11 15 19]


In [211]:
x = np.arange(12).reshape(3,4)
print(x)
print(x[-1:,].shape)
print(x[-1:,])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(1, 4)
[[ 8  9 10 11]]


In [212]:
x = np.array([[0, 1], [1, 1], [2, 2]])
y = x.sum(-1)
print(x[y < 2, :])

[[0 1]]


In [221]:
x = np.arange(30).reshape(2,3,5)
b = np.array([True,False]).reshape(2,)
print(x,end='\n\n')
print(x[b],end='\n\n')
print(x[b,:,1:3],end='\n\n')

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]

[[[ 1  2]
  [ 6  7]
  [11 12]]]



In [231]:
x = np.arange(30).reshape(3,5,2)
print(x[-1, 2:-1, -1])
x

[25 27]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [233]:
(np.random.rand(4,1,1,7) * np.random.rand(3,1)).shape

(4, 1, 3, 7)

In [234]:
x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [235]:
x = np.array([[0, 1], [1, 1], [2, 2]])
print(x.sum(-1))

[1 2 4]


In [236]:
print(np.repeat(3, 4))

[3 3 3 3]


In [237]:
x = np.array([[-1,0,1], [-2, 0, 2]])

y = np.zeros_like(x)
print(y)

[[0 0 0]
 [0 0 0]]
