In [1]:
import pandas as pd

In [6]:
cancer_set = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data', 
                        header = None)

In [7]:
cancer_set

0  1      2      3       4       5        6        7        8   \
0      842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010   
1      842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690   
2    84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740   
3    84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140   
4    84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800   
..        ... ..    ...    ...     ...     ...      ...      ...      ...   
564    926424  M  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390   
565    926682  M  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400   
566    926954  M  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251   
567    927241  M  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140   
568     92751  B   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000   

          9   ...      22     23      24      25       26       27      28  \
0    0.14710  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.07017  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.12790  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.10520  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.10430  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.13890  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.09791  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05302  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.15200  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.00000  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         29      30       31  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 32 columns]

In [11]:
cancer_features = cancer_set.iloc[:,2:]
cancer_features.shape

(569, 30)

In [13]:
print(cancer_features)
print(type(cancer_features))

cancer_features = cancer_features.values
print(cancer_features)
print(type(cancer_features))

        2      3       4       5        6        7        8        9       10  \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          11  ...      22  

In [14]:
cancer_features_names = ['mean radius', 
'mean texture', 'mean perimeter', 
'mean area', 'mean smoothness', 
'mean compactness', 'mean concavity',
'mean concave points', 'mean symmetry',
'mean fractal dimension','radius error',
'texture error','perimeter error',
'area error', 'smoothness error',
'compactness error','concavity error',
'concave points error','symmetry error',
'fractal dimension error','worst radius',
'worst texture', 'worst perimeter', 
'worst area','worst smoothness', 
'worst compactness', 'worst concavity',
'worst concave points','worst symmetry',
'worst fractal dimension']

In [22]:
cancer_target = cancer_set.iloc[:,1]

# Replacing 'M' with 0 and 'B' with 1
cancer_target = cancer_target.replace(['M','B'],[0,1])

# Converting to numpy array
cancer_target = cancer_target.values

print(cancer_target)
print(type(cancer_target))
print(cancer_target.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [23]:
import sklearn.datasets as datasets

In [24]:
cancer = datasets.load_breast_cancer()

In [25]:
cancer.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [26]:
cancer_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [28]:
iris = datasets.load_iris()

In [30]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [31]:
# Standardization
import sklearn.preprocessing as preprocessing

In [36]:
standardizer = preprocessing.StandardScaler()
standardizer = standardizer.fit(cancer.data)
breast_cancer_standardized = standardizer.transform(cancer.data)

print(breast_cancer_standardized.mean(axis = 0))
print(breast_cancer_standardized.std(axis = 0))

[-3.16286735e-15 -6.53060890e-15 -7.07889127e-16 -8.79983452e-16
  6.13217737e-15 -1.12036918e-15 -4.42138027e-16  9.73249991e-16
 -1.97167024e-15 -1.45363120e-15 -9.07641468e-16 -8.85349205e-16
  1.77367396e-15 -8.29155139e-16 -7.54180940e-16 -3.92187747e-16
  7.91789988e-16 -2.73946068e-16 -3.10823423e-16 -3.36676596e-16
 -2.33322442e-15  1.76367415e-15 -1.19802625e-15  5.04966114e-16
 -5.21317026e-15 -2.17478837e-15  6.85645643e-16 -1.41265636e-16
 -2.28956670e-15  2.57517109e-15]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [37]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0,10)).fit(cancer.data)
breast_cancer_minmaxscaled10 = min_max_scaler.transform(cancer.data)
breast_cancer_minmaxscaled10

array([[5.21037437, 0.22658099, 5.45988529, ..., 9.12027491, 5.98462448,
        4.18863964],
       [6.43144493, 2.72573554, 6.15783291, ..., 6.39175258, 2.33589592,
        2.22878132],
       [6.01495575, 3.90260399, 5.95743211, ..., 8.35051546, 4.03705894,
        2.13433032],
       ...,
       [4.55251077, 6.21237741, 4.45788128, ..., 4.87285223, 1.28720678,
        1.51908697],
       [6.44564343, 6.63510315, 6.65537972, ..., 9.10652921, 4.97141731,
        4.52315361],
       [0.36868759, 5.01521813, 0.28539838, ..., 0.        , 2.57441356,
        1.00682146]])

In [59]:
min_max_scaler = preprocessing.MinMaxScaler().fit(cancer.data)
breast_cancer_minmaxscaled = min_max_scaler.transform(cancer.data)
breast_cancer_minmaxscaled

array([[0.52103744, 0.0226581 , 0.54598853, ..., 0.91202749, 0.59846245,
        0.41886396],
       [0.64314449, 0.27257355, 0.61578329, ..., 0.63917526, 0.23358959,
        0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, ..., 0.83505155, 0.40370589,
        0.21343303],
       ...,
       [0.45525108, 0.62123774, 0.44578813, ..., 0.48728522, 0.12872068,
        0.1519087 ],
       [0.64456434, 0.66351031, 0.66553797, ..., 0.91065292, 0.49714173,
        0.45231536],
       [0.03686876, 0.50152181, 0.02853984, ..., 0.        , 0.25744136,
        0.10068215]])

In [38]:
max_abs_scaler = preprocessing.MaxAbsScaler().fit(cancer.data)
breast_cancer_maxabsscaled = max_abs_scaler.transform(cancer.data)
breast_cancer_maxabsscaled

array([[0.63998577, 0.26425662, 0.65145889, ..., 0.91202749, 0.69313046,
        0.57301205],
       [0.73176805, 0.45239308, 0.70503979, ..., 0.63917526, 0.41428141,
        0.42901205],
       [0.70046247, 0.54098778, 0.68965517, ..., 0.83505155, 0.54429045,
        0.42207229],
       ...,
       [0.59053718, 0.71486762, 0.57453581, ..., 0.48728522, 0.33413679,
        0.37686747],
       [0.73283529, 0.74669043, 0.74323607, ..., 0.91065292, 0.6156975 ,
        0.59759036],
       [0.27605834, 0.62474542, 0.25421751, ..., 0.        , 0.43250979,
        0.33922892]])

In [42]:
normalizer = preprocessing.Normalizer(norm='l1').fit(cancer.data)
breast_cancer_normalized = normalizer.transform(cancer.data)
breast_cancer_normalized

array([[5.04461573e-03, 2.91067878e-03, 3.44346198e-02, ...,
        7.44214015e-05, 1.29017660e-04, 3.33410122e-05],
       [5.49864230e-03, 4.75016401e-03, 3.55259874e-02, ...,
        4.97203436e-05, 7.35112606e-05, 2.37962634e-05],
       [5.81273050e-03, 6.27326171e-03, 3.83776011e-02, ...,
        7.17365928e-05, 1.06660210e-04, 2.58546946e-05],
       ...,
       [7.00344278e-03, 1.18467875e-02, 4.56911357e-02, ...,
        5.98245895e-05, 9.35761210e-05, 3.29921220e-05],
       [5.68390968e-03, 8.09267334e-03, 3.86561042e-02, ...,
        7.31182555e-05, 1.12767664e-04, 3.42138252e-05],
       [1.18802525e-02, 3.75697675e-02, 7.33636209e-02, ...,
        0.00000000e+00, 4.39538722e-04, 1.07764300e-04]])

In [45]:
binarizer = preprocessing.Binarizer(threshold=3.0).fit(cancer.data)
breast_cancer_binarized = binarizer.transform(cancer.data)
breast_cancer_binarized[:5,:7]

array([[1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0.]])

In [46]:
onehotencoder = preprocessing.OneHotEncoder()
onehotencoder = onehotencoder.fit([[1], [1], [1], [2], [2], [1]])

# Transforming category values 1 and 2 to one-hot vectors
print(onehotencoder.transform([[1]]).toarray())
print(onehotencoder.transform([[2]]).toarray())

[[1. 0.]]
[[0. 1.]]


In [48]:
imputer = preprocessing.Imputer(missing_values='NaN', strategy='mean')

imputer = imputer.fit(breast_cancer.data)
breast_cancer_imputed = imputer.transform(breast_cancer.data)
breast_cancer_imputed

AttributeError: module 'sklearn.preprocessing' has no attribute 'Imputer'

In [53]:
from sklearn.impute import SimpleImputer
import numpy as np
imp = SimpleImputer(missing_values=np.NaN, strategy="mean" ).fit(cancer.data)
breast_cancer_imputed = imp.transform(cancer.data)
breast_cancer_imputed

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [54]:
labelencoder = preprocessing.LabelEncoder().fit(cancer.target_names)
bc_labelencoded = labelencoder.transform(cancer.target_names)
bc_labelencoded

array([1, 0], dtype=int64)

In [57]:
labels = ['malignant', 'benign', 'malignant', 'benign']
labelencoder = preprocessing.LabelEncoder()
labelencoder = labelencoder.fit(labels)
bc_labelencoded = labelencoder.transform(cancer.target_names)
bc_labelencoded

array([1, 0], dtype=int64)

In [61]:
import sklearn.datasets as datasets
import sklearn.preprocessing as preprocessing
iris = datasets.load_iris()
normalizer = preprocessing.Normalizer().fit(iris.data)
iris_normalized = normalizer.transform(iris.data)
print(iris_normalized.mean(axis=0))

[0.75140029 0.40517418 0.45478362 0.14107142]


In [64]:
import sklearn.datasets as datasets
import sklearn.preprocessing as preprocessing
iris = datasets.load_iris()

onehotencoder = preprocessing.OneHotEncoder().fit(iris.target.reshape(-1,1))
iris_target_onehot = onehotencoder.transform(iris.target.reshape(-1,1))
print(iris_target_onehot.toarray()[[0,50,100]])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
import sklearn.datasets as datasets
import sklearn.preprocessing as preprocessing
from sklearn.impute import SimpleImputer
import numpy as np
iris = datasets.load_iris()

iris.data[:50] = np.NaN

imp = SimpleImputer(missing_values=np.NaN, strategy="mean" ).fit(iris.data)
iris_imputed = imp.transform(iris.data)
print(iris_imputed.mean(axis=0))

[6.262 2.872 4.906 1.676]


In [73]:
x = [[7.8], [1.3], [4.5], [0.9]]
print(preprocessing.Binarizer().fit(x).transform(x).shape)

(4, 1)


In [76]:
# importing required modules and loading cancer dataset
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
cancer = datasets.load_breast_cancer()


# Building a Model of KNN classifier
X_train, X_test, Y_train, Y_test = train_test_split(cancer.data, cancer.target,
                                                    stratify = cancer.target,
                                                    random_state = 42)
knn_classifier = KNeighborsClassifier()
knn_classifier = knn_classifier.fit(X_train, Y_train)


# Determining Accuracy of the Model
print('Accuracy of Train Data :', knn_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', knn_classifier.score(X_test,Y_test))


Accuracy of Train Data : 0.9460093896713615
Accuracy of Test Data : 0.9300699300699301


In [81]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()

X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target,
                                                    stratify = iris.target, 
                                                    random_state = 30)
print(X_train.shape)
print(X_test.shape)

(112, 4)
(38, 4)


In [82]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

iris = datasets.load_iris()

X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target,
                                                    stratify = iris.target, 
                                                    random_state = 30)

knn_classifier = KNeighborsClassifier().fit(X_train,Y_train)
print(knn_classifier.score(X_train,Y_train))
print(knn_classifier.score(X_test,Y_test))

0.9821428571428571
0.9473684210526315


In [85]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

iris = datasets.load_iris()

X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target,
                                                    stratify = iris.target, 
                                                    random_state = 30)

knn_classifier = KNeighborsClassifier(n_neighbors=3).fit(X_train,Y_train)
accuracy0 = knn_classifier.score(X_test,Y_test)
n_neighbors = 3
for i in range(4,11):
    knn_classifier = KNeighborsClassifier(n_neighbors=i).fit(X_train,Y_train)
    accuracy1 = knn_classifier.score(X_test,Y_test)
    if accuracy1 > accuracy0:
        n_neighbors = i
    accuracy0 = accuracy1
print(n_neighbors)

6


In [94]:
# Decision Trees

# importing required modules, load cancer dataset, and create train and test data sets
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import sklearn.datasets as datasets

cancer = datasets.load_breast_cancer()
X_train, X_test, Y_train, Y_test = train_test_split( cancer.data, cancer.target,
                                                   stratify = cancer.target,
                                                   random_state = 30)
dt_classifier = DecisionTreeClassifier()
dt_classifier = dt_classifier.fit(X_train, Y_train)


# Determining Accuracy of the Model
print('Accuracy of Train Data :', dt_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', dt_classifier.score(X_test,Y_test))

Accuracy of Train Data : 1.0
Accuracy of Test Data : 0.9230769230769231


In [92]:
# Fine Tuning the Above Model
dt_classifier = DecisionTreeClassifier(max_depth= 2)
dt_classifier = dt_classifier.fit(X_train, Y_train)

print('Accuracy of Train Data :', dt_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', dt_classifier.score(X_test,Y_test))

Accuracy of Train Data : 0.9647887323943662
Accuracy of Test Data : 0.9020979020979021


In [123]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
import numpy as np
np.random.seed(100)

boston = datasets.load_boston()
X_train, X_test, Y_train, Y_test = train_test_split( boston.data, boston.target, random_state = 30)
print(X_train.shape)
print(X_test.shape)

(379, 13)
(127, 13)


In [122]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
import numpy as np
np.random.seed(100)

boston = datasets.load_boston()
X_train, X_test, Y_train, Y_test = train_test_split( boston.data, boston.target, random_state = 30)
dt_reg = DecisionTreeRegressor()
dt_reg = dt_reg.fit(X_train, Y_train)

print(dt_reg.score(X_train, Y_train))
print(dt_reg.score(X_test, Y_test))
print(dt_reg.predict(X_test[:2]))

1.0
0.7883979988271616
[32.9 23.9]


In [136]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
import numpy as np
np.random.seed(100)

boston = datasets.load_boston()
X_train, X_test, Y_train, Y_test = train_test_split( boston.data, boston.target)#, random_state = 30)

dt_reg = DecisionTreeRegressor(max_depth=2).fit(X_train, Y_train)
accuracy0 = dt_reg.score(X_test, Y_test)
depth = 2
print(accuracy0)
for i in range(3,6):
    dt_reg = DecisionTreeRegressor(max_depth=i).fit(X_train, Y_train)
    accuracy1 = dt_reg.score(X_test, Y_test)
    print(accuracy1)
    if accuracy1 > accuracy0:
        depth = i
#     print(accuracy1)
#     print(max_depth)
    
    accuracy0 = accuracy1
print(depth)

0.6189051959855576
0.699781997031047
0.737701724177952
0.7824055448239499
5


In [140]:
# Demo of Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

X_train, X_test, Y_train, Y_test = train_test_split( cancer.data, cancer.target,
                                                   stratify = cancer.target,
                                                   random_state = 42)

rf_classifier = RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, Y_train)
print('Accuracy of Train Data :', rf_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', rf_classifier.score(X_test,Y_test))

Accuracy of Train Data : 1.0
Accuracy of Test Data : 0.958041958041958


In [141]:
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, Y_train, Y_test = train_test_split( cancer.data, cancer.target,
                                                   stratify = cancer.target)

rf_classifier = RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, Y_train) 

print('Accuracy of Train Data :', rf_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', rf_classifier.score(X_test,Y_test))

Accuracy of Train Data : 1.0
Accuracy of Test Data : 0.965034965034965


In [142]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
import numpy as np
np.random.seed(100)

boston = datasets.load_boston()
X_train, X_test, Y_train, Y_test = train_test_split( boston.data, boston.target, random_state = 30)
print(X_train.shape)
print(X_test.shape)

(379, 13)
(127, 13)


In [143]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import numpy as np
np.random.seed(100)

boston = datasets.load_boston()
X_train, X_test, Y_train, Y_test = train_test_split( boston.data, boston.target, random_state = 30)
rf_reg = RandomForestRegressor()
rf_reg = rf_reg.fit(X_train, Y_train)

print(rf_reg.score(X_train, Y_train))
print(rf_reg.score(X_test, Y_test))
print(rf_reg.predict(X_test[:2]))

0.887575241889432
0.8413867238252251
[21.03543307  8.8047619 ]


In [145]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import numpy as np
np.random.seed(100)

boston = datasets.load_boston()
X_train, X_test, Y_train, Y_test = train_test_split( boston.data, boston.target, random_state = 30)

rf_reg = RandomForestRegressor(max_depth=3,n_estimators=50)
rf_reg = rf_reg.fit(X_train, Y_train)
accuracy0 = rf_reg.score(X_test, Y_test)
max_depth = 3
n_estimators = 50

for i in range(3,6):
    for j in [50,100,200]:
        rf_reg = RandomForestRegressor(max_depth=i,n_estimators=j)
        rf_reg = rf_reg.fit(X_train, Y_train)
        accuracy1 = rf_reg.score(X_test, Y_test)
        
        if accuracy1 > accuracy0:
            max_depth = i
            n_estimators = j
        accuracy0 = accuracy1

print((max_depth, n_estimators))

(5, 100)


In [152]:
# Demo of Support Vector Classification
# An example of creating an SVM classifier is shown below.

# The shown model overfits the training data.

from sklearn.svm import SVC

cancer = datasets.load_breast_cancer()
X_train, X_test, Y_train, Y_test = train_test_split( cancer.data, cancer.target,
                                                   stratify = cancer.target)

svm_classifier = SVC()
svm_classifier = svm_classifier.fit(X_train, Y_train)
print('Accuracy of Train Data :', svm_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', svm_classifier.score(X_test,Y_test))

Accuracy of Train Data : 0.9225352112676056
Accuracy of Test Data : 0.9090909090909091


In [154]:
# Improving Accuracy Using Scaled Data
# In the following example, scaled input data is used to improve the accuracy of SVM classifier.

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
cancer = datasets.load_breast_cancer()


X_train, X_test, Y_train, Y_test = train_test_split( cancer.data, cancer.target,
                                                   stratify = cancer.target)

svm_classifier = SVC()
svm_classifier = svm_classifier.fit(X_train, Y_train)
print('Accuracy of Train Data :', svm_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', svm_classifier.score(X_test,Y_test))

print()

standardizer = StandardScaler()
standardizer = standardizer.fit(cancer.data)
cancer_standardized  = standardizer.transform(cancer.data)
X_train, X_test, Y_train, Y_test = train_test_split( cancer_standardized, cancer.target,
                                                   stratify = cancer.target)
svm_classifier = SVC()
svm_classifier = svm_classifier.fit(X_train, Y_train)
print('Accuracy of Train Data :', svm_classifier.score(X_train,Y_train))
print('Accuracy of Test Data :', svm_classifier.score(X_test,Y_test))


Accuracy of Train Data : 0.9178403755868545
Accuracy of Test Data : 0.9230769230769231

Accuracy of Train Data : 0.9859154929577465
Accuracy of Test Data : 0.986013986013986


In [156]:
# Viewing the Classification Report

from sklearn import metrics

Y_pred = svm_classifier.predict(X_test)
print('Classification report : \n',metrics.classification_report(Y_test, Y_pred))

Classification report : 
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        53
           1       0.99      0.99      0.99        90

    accuracy                           0.99       143
   macro avg       0.99      0.99      0.99       143
weighted avg       0.99      0.99      0.99       143



In [158]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split

digits = datasets.load_digits()

X_train, X_test, Y_train, Y_test = train_test_split(digits.data, digits.target, random_state=30, stratify = digits.target)
print(X_train.shape)
print(X_test.shape)

(1347, 64)
(450, 64)


In [159]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
    

digits = datasets.load_digits()
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, digits.target, random_state=30, stratify = digits.target)

svm_clf = SVC()
svm_clf = svm_clf.fit(X_train, Y_train)

print(svm_clf.score(X_test, Y_test))

0.9822222222222222


In [161]:
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
    
digits = datasets.load_digits()

standardizer = StandardScaler().fit(digits.data)
digits_standardized = standardizer.transform(digits.data)

X_train, X_test, Y_train, Y_test = train_test_split(digits_standardized, digits.target, random_state=30, stratify = digits.target)

svm_clf2 = SVC()
svm_clf2 = svm_clf2.fit(X_train, Y_train)

print(svm_clf2.score(X_test, Y_test))

0.9733333333333334


In [169]:
# Demo of KMeans
# An example of performing KMeans clustering is shown below

from sklearn.cluster import KMeans

kmeans_cluster = KMeans(n_clusters=2)
kmeans_cluster = kmeans_cluster.fit(X_train) 

kmeans_cluster.predict(X_test)

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [170]:
# Evaluation with scikit-learn
from sklearn import metrics

print(metrics.homogeneity_score(kmeans_cluster.predict(X_test), Y_test))
print(metrics.completeness_score(kmeans_cluster.predict(X_test), Y_test))
print(metrics.v_measure_score(kmeans_cluster.predict(X_test), Y_test))
print(metrics.adjusted_rand_score(kmeans_cluster.predict(X_test), Y_test))

0.8590276495020881
0.5149173437707478
0.6438805595172867
0.5268896419625755


In [179]:
import sklearn.datasets as datasets
from sklearn.cluster import KMeans
from sklearn import metrics

iris = datasets.load_iris()

km_cls = KMeans(n_clusters=3)
km_cls = km_cls.fit(iris.data)

print(metrics.homogeneity_score(km_cls.predict(iris.data),iris.target))

0.7649861514489815


In [196]:
import sklearn.datasets as datasets
from sklearn.cluster import AgglomerativeClustering
from sklearn import metrics

iris = datasets.load_iris()

agg_cls = AgglomerativeClustering(n_clusters=3)
agg_cls = agg_cls.fit(iris.data)

print(metrics.homogeneity_score(agg_cls.labels_,iris.target))

0.7795958005591144


In [198]:
import sklearn.datasets as datasets
from sklearn.cluster import AffinityPropagation
from sklearn import metrics

iris = datasets.load_iris()

af_cls = AffinityPropagation()
af_cls = af_cls.fit(iris.data)

print(metrics.homogeneity_score(af_cls.labels_,iris.target))

0.5278221404408368


C:\Users\Anurag\anaconda3\lib\site-packages\sklearn\cluster\_affinity_propagation.py:146: FutureWarning: 'random_state' has been introduced in 0.23. It will be set to None starting from 0.25 which means that results will differ at every function call. Set 'random_state' to None to silence this warning, or to 0 to keep the behavior of versions <0.23.
  warnings.warn(("'random_state' has been introduced in 0.23. "


In [199]:
import sklearn.preprocessing as preprocessing

x = [[7.8], [1.3], [4.5], [0.9]]
print(preprocessing.Binarizer().fit(x).transform(x).shape)

(4, 1)


In [201]:
regions = ['HYD', 'CHN', 'MUM', 'HYD', 'KOL', 'CHN']
print(preprocessing.LabelEncoder().fit(regions).transform(regions))

[1 0 3 1 2 0]
